export const proizvodi = [
    {'name': 'TEFAL Multicooker 8in1',
      'price':'60',
      'description': 'Upoznajte 8 u 1, kompujterizovani aparat za kuvanje pirinča koji može sve da skuva. Kada se kuvanje završi, on automatski održava najbolju temperaturu posluživanja hrane koju ste pripremili sve dok dok ne poželite da uživate u njoj. Uz 8 programa kuvanja, kuvajte pirinač i žitarice, kuvajte na pari ili sporo kuvajte sastojke do savršenih rezultata.',
      'url':'assets/img/folder1/slika1.png',
      'url1': 'assets/img/folder1/slika1.png',
      'url2': 'assets/img/folder1/slika2.png',
      'url3': 'assets/img/folder1/slika3.png',
      'url4': 'assets/img/folder1/slika4.png',
      
    },
    {'name': 'TEFAL ActiFry Express XL',
      'price':'40',
      'description': ' do 30% brža*** nego originalni model, može da pripremi 1,7 kg pomfrita za manje od 30 minuta sa samo jednom kašikom ulja! Pripremanje hrane je samo 3 minuta duže nego u standardnoj fritezi, vreme zagrevanja je uračunato u ukupno vreme pripreme hrane!Ekskluzivna patentirana nova tehnologija koja dokazuje performanse ActiFry',
      'url':'assets/img/folder2/slika1.png',
      'url1': 'assets/img/folder2/slika1.png',
      'url2': 'assets/img/folder2/slika2.png',
      'url3': 'assets/img/folder2/slika3.png',
      'url4': 'assets/img/folder2/slika4.png',
      
    },
    {'name': 'TEFAL Vitacuisine Compact',
      'price':'30',
      'description': 'Upoznajte Vitacuisine Compact, aparat za kuvanje na pari koji će vaše obroke obogatiti mnoštvom vitamina! Možete da pripremite 3 obroka zahvaljujući odvojenim korpama. Više ne morate da birate između predjela, glavnog jela ili dezerta – možete istovremeno da ih pripremite! Nema potrebe da nadzirete spremanje obroka, kada aparat završi s kuvanjem, automatski se isključuje i održava vaš obrok toplim sve dok ne poželite da ga konzumirate.',
      'url':'assets/img/folder3/slika1.png',
      'url1': 'assets/img/folder3/slika1.png',
      'url2': 'assets/img/folder3/slika2.png',
      'url3': 'assets/img/folder3/slika3.png',
      'url4': 'assets/img/folder3/slika4.png',
      
    },
    {'name': 'TEFAL Masterchef Gourmet ',
      'price':'55',
      'description': 'Masterchef Gourmet + omogućava vam da uživate u pripremi kolača. Aparat je specijalno dizajniran za ljude koje žele da nadmaše sebe. Upotrebite inspiraciju koja nadolazi.Zahvaljujući specijalno dizajniranom trećem dodatku, Flex Whisk veoma lako doseže do dna posude, razbija sve sastojke i daje vazdušaste rezultate za veoma kratko vreme! Umutite 10 belanaca, napravite 40 kapkejkova i 3 velika testa za picu zahvaljujući posudi kapaciteta 4,6L.Mešenje, mešanje, mućenje uz pomoć dodataka: veoma otporna livena metalna kuka za testo, dodatak za mešanje i Flex Whisk (fleksibilna žica za mućenje) su idealni za svakodnevnu upotrebu.',
      'url':'assets/img/folder4/slika1.png',
      'url1': 'assets/img/folder4/slika1.png',
      'url2': 'assets/img/folder4/slika2.png',
      'url3': 'assets/img/folder4/slika3.png',
      'url4': 'assets/img/folder4/slika4.png',
    },
    {'name': 'TEFAL Infiny Press',
      'price':'45',
      'description': 'Zahvaljujući rotacionom navoju, Infiny Press Revolution sokovnik konstantnim, blagim pritiskom cedi sav sok iz svakog sastojka. Sporo rotirajući mehanizam pruža delikatan pritisak koji omogućava da se iscedi ono najbolje iz svih vrsta voća, povrća ili čak svežeg bilja. Infiny Press Revolution zadržava ne samo neponovljiv ukus svakog svežeg sastojka, već i svih drugih hranljivih sastojaka. Zahvaljujući njegovoj tehnologiji pravljenja soka, on cedi 35% više soka, 30% više vitamina C i 75% više antioksidanasa nego tradicionalni centrifugalni sokovnik.',
      'url':'assets/img/folder5/slika1.png',
      'url1': 'assets/img/folder5/slika1.png',
      'url2': 'assets/img/folder5/slika2.png',
      'url3': 'assets/img/folder5/slika3.png',
      'url4': 'assets/img/folder5/slika4.png',
    },
    {'name': 'TEFAL Fresh Express +',
      'price':'20',
      'description': 'Fresh Express + sa 5 različitih konusnih dodataka omogućava vam da rendate, sečete na kriške, iseckate ili rebrasto nasečete povrće, voće, sir ili čokoladu direktno na tanjir, spremno za posluživanje!  Dodaci su obojeni različitim bojama pomoći će vam da lako odaberete izaberete dodatak koji vam je potreban a takođe dodaju boje vašoj kuhinji. Osim toga, Fresh Express + ima veliki otvor za unos hrane a to znači da više ne morate unapred seći povrće! ',
      'url':'assets/img/folder6/slika1.png',
      'url1': 'assets/img/folder6/slika1.png',
      'url2': 'assets/img/folder6/slika2.png',
      'url3': 'assets/img/folder6/slika3.png',
      'url4': 'assets/img/folder6/slika4.png',
    },
    {'name': 'TEFAL Pain & Délices ',
      'price':'100',
      'description': 'Pain & Délices je najkompletnija i najfunkcionalnija Tefal kućna pekara. Vaša mašta neće imati limit! Uživajte u ukusima ne samo svežeg i ukusnog domaćeg hleba nego i u pripremi pizza testa, sveže paste, džema, ovsene kaše i žitarica i mlečnih priprema. U 20 programa različitih priprema zdravog i ukusnog hleba i kolača ulaze i 3 bezglutenska programa. Otkrijte ih koristeći knjigu recepata! Zahvaljujući 3 posebna programa + posudu za jogurt od 1L, sada možete vašoj porodici da pripremite i mlečne proizvode: jogurt & tečni jogurt i mladi sir. Bilo da malo ili u većoj meri konzumirate hleb, bilo da živite sami ili sa porodicom, imate izbor 3 odabira veličine od 500g do 1kg. Kompaktna, Pain & Delices kućna pekara je modernog i elgantnog dizajna, savršeno se uklapa u vašu kuhinju. Uživajte u ukusu svežeg i toplog hleba zahvaljujući funkciji odloženog starta i do 15 sati: šta je slađe od mirisa svežeg hleba ujutru! ',
      'url':'assets/img/folder7/slika1.png',
      'url1': 'assets/img/folder7/slika1.png',
      'url2': 'assets/img/folder7/slika2.png',
      'url3': 'assets/img/folder7/slika3.png',
      'url4': 'assets/img/folder7/slika4.png',
    },
    {'name': 'TEFAL OptiGrill+ Snacking & Baking GC714834',
      'price':'70',
      'description': 'Upoznajte OptiGrill+ Snacking&Baking, našu inovaciju sa manuelnim načinom rada koji sadrži četiri nivoa temperature za beskrajne mogućnosti kuvanja. Za još više mogućnosti tu je poseban dodatak za pečenje koji omogućava da pečete, podgrevate ili samo zapečete hranu zahvaljujući manuelnom načinu rada i 4 temperature.Termoizolovane ručke za vašu bezbednost i mogućnost pranja u mašini za posuđa, za veću praktičnost. Unapređen tehnologijom "Automatskog senzora kuvanja", OptiGrill+ odmah detektuje broj namirnica na površini za pečenje i procenjuje debljinu namirnice kako bi automatski podesio temperaturu i vreme za pečenje za savršene rezultate. Svetolosni indikator i zvučni sistem omogućuju direktni nadzor za veoma precizno kuvanje, pripremu mesa baš kako volite: slabo pečeno, srednje pečeno, dobro pečeno. 6 programa za kuvanje: burgeri, živina, sendviči, kobasice, crveno meso i riba plus program za smrznutu hranu i manuelni način rada sa 4 podešavanja temperature. Dodatna svojstva uključuju nelepljive aluminijumske ploče, površine 600 cm2, dovoljno za posluživanje 2 do 4 osobe i velika tacna za sokove, pod uglom od 7°. ',
      'url':'assets/img/folder8/slika1.png',
      'url1': 'assets/img/folder8/slika1.png',
      'url2': 'assets/img/folder8/slika2.png',
      'url3': 'assets/img/folder8/slika3.png',
      'url4': 'assets/img/folder8/slika4.png',
    }
];